/********************************************************************
* mainDic.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error mainDic.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablemainDic();
extern void G__cpp_setup_inheritancemainDic();
extern void G__cpp_setup_typetablemainDic();
extern void G__cpp_setup_memvarmainDic();
extern void G__cpp_setup_globalmainDic();
extern void G__cpp_setup_memfuncmainDic();
extern void G__cpp_setup_funcmainDic();
extern void G__set_cpp_environmentmainDic();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "mymainframe.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__mainDicLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__mainDicLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__mainDicLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__mainDicLN_string;
extern G__linked_taginfo G__mainDicLN_basic_ostringstreamlEcharcOchar_traitslEchargRcOallocatorlEchargRsPgR;
extern G__linked_taginfo G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mainDicLN_TList;
extern G__linked_taginfo G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mainDicLN_TQObjSender;
extern G__linked_taginfo G__mainDicLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__mainDicLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mainDicLN_TCanvas;
extern G__linked_taginfo G__mainDicLN_TH1F;
extern G__linked_taginfo G__mainDicLN_TThread;
extern G__linked_taginfo G__mainDicLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__mainDicLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__mainDicLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__mainDicLN_TGraph;
extern G__linked_taginfo G__mainDicLN_TLine;
extern G__linked_taginfo G__mainDicLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mainDicLN_TGWindow;
extern G__linked_taginfo G__mainDicLN_TGCompositeFrame;
extern G__linked_taginfo G__mainDicLN_TGTextButton;
extern G__linked_taginfo G__mainDicLN_TGHorizontalFrame;
extern G__linked_taginfo G__mainDicLN_TGMainFrame;
extern G__linked_taginfo G__mainDicLN_TGGroupFrame;
extern G__linked_taginfo G__mainDicLN_TGCheckButton;
extern G__linked_taginfo G__mainDicLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__mainDicLN_TGTab;
extern G__linked_taginfo G__mainDicLN_TGNumberEntry;
extern G__linked_taginfo G__mainDicLN_TGLabel;
extern G__linked_taginfo G__mainDicLN_TGTextView;
extern G__linked_taginfo G__mainDicLN_DataStr;
extern G__linked_taginfo G__mainDicLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR;
extern G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mainDicLN_MyMainFrame;
extern G__linked_taginfo G__mainDicLN_pairlEboolcOboolgR;

/* STUB derived class for protected member access */
